"""transaction table altered

Revision ID: 0cf0ed97169f
Revises: 0e93f33d00d2
Create Date: 2025-01-21 13:26:47.002567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf0ed97169f'
down_revision: Union[str, None] = '0e93f33d00d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_sender_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_receiver_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_receiver_wallet_id_fkey', 'transactions', 'wallets', ['receiver_wallet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_sender_wallet_id_fkey', 'transactions', 'wallets', ['sender_wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
