"""pin added for user

Revision ID: 4abbd46b9036
Revises: f65cb3f0386a
Create Date: 2025-01-16 00:06:49.295063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abbd46b9036'
down_revision: Union[str, None] = 'f65cb3f0386a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    # ### end Alembic commands ###
