"""altered Budget category columns

Revision ID: 8bf17e811205
Revises: c96c2ac62539
Create Date: 2025-01-10 14:14:16.176146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf17e811205'
down_revision: Union[str, None] = 'c96c2ac62539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_budget_categories_user_id'), 'budget_categories', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'budget_categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_categories', type_='unique')
    op.drop_index(op.f('ix_budget_categories_user_id'), table_name='budget_categories')
    # ### end Alembic commands ###
