"""Budget category name

Revision ID: c95496f898f5
Revises: 4abbd46b9036
Create Date: 2025-01-17 19:33:54.451359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95496f898f5'
down_revision: Union[str, None] = '4abbd46b9036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budget_categories_name_key', 'budget_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('budget_categories_name_key', 'budget_categories', ['name'])
    # ### end Alembic commands ###
