"""over spending budget limit

Revision ID: f8566a5fad58
Revises: e2b63c6f7b7e
Create Date: 2025-01-12 11:43:56.255685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8566a5fad58'
down_revision: Union[str, None] = 'e2b63c6f7b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('over_spend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'over_spend')
    # ### end Alembic commands ###
