"""sender and receiver column added

Revision ID: fc05fbae3a10
Revises: 7e81432d2a14
Create Date: 2025-01-14 17:08:38.236709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc05fbae3a10'
down_revision: Union[str, None] = '7e81432d2a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'wallets', ['sender_wallet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'wallets', ['receiver_wallet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'receiver_wallet_id')
    op.drop_column('transactions', 'sender_wallet_id')
    # ### end Alembic commands ###
